name: Check Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch and target for PR
        run: |
          branch_name=${GITHUB_HEAD_REF}
          echo "Pull Request Branch: $branch_name"

          target_branch=${GITHUB_BASE_REF}
          echo "Target Branch: $target_branch"

          regex="^(feature|fix|chore)/+.*$"

          if [[ "$branch_name" =~ $regex ]]; then
            echo "Pull request branch passes the branch name requirement."
            if [[ "$target_branch" != "main" ]]; then
              echo "Error: Pull requests with 'feature/', 'fix/', or 'chore/' prefixes must target 'main'."
              exit 1
            fi
          else
            echo "Error: Pull request branch name must be prefixed with 'feature/', 'fix/', or 'chore/'."
            exit 1
          fi
        shell: bash